def show_menu() :
        print('+','-' * 24,'+',sep = '')
        print('|','1) 添加学生信息'.center(18),'|',sep = '')
        print('|','2) 显示学生信息'.center(18),'|',sep = '')
        print('|','3) 删除学生信息'.center(18),'|',sep = '')
        print('|','4) 修改学生信息'.center(18),'|',sep = '')
        print('|','5) 按成绩降序排列'.center(17),'|',sep = '')
        print('|','6) 按成绩升序排列'.center(17),'|',sep = '')
        print('|','7) 按年龄降序排列'.center(17),'|',sep = '')
        print('|','8) 按年龄升序排列'.center(17),'|',sep = '')
        print('|','9) 读取学生数据'.center(18),'|',sep = '')
        print('|','10) 保存信息到文件'.center(17),'|',sep = '')
        print('|','Q) 结束程序　　 '.center(18),'|',sep = '')
        print('+','-' * 24,'+',sep = '')