name=' alaX '
print('a:',name.strip(),sep = '')
print('b:',name.startswith('al'))
print('c：',name.endswith('x'))
print('d:',name.replace('l','p'))
print('e:',name.split('l'))
print("f:",'''[' a','ax ']''')
print('g:',name.upper())
print("h:",name.lower())
print('i:',name[2:3])
print('j:',name[0:4])
print('k:',name[-3:-1])
print('l:',name.find('e'))